# Generated by Django 5.0.4 on 2026-04-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_shoplifting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplifting',
            name='video_path',
            field=models.CharField(max_length=500),
        ),
    ]
