# Generated by Django 5.0.4 on 2026-04-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alter_shoplifting_video_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplifting',
            name='video_path',
            field=models.FileField(upload_to='shoplifting_videos/'),
        ),
    ]
