# Generated by Django 5.0.4 on 2026-04-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_alter_shoplifting_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplifting',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
